name: PR
on:
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  install:
    runs-on: ubuntu-latest
    name: install
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ github.sha }}-${{ github.run_number }}
      - run: yarn --frozen-lockfile

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ github.sha }}-${{ github.run_number }}
      - run: yarn lint

  test:
    name: test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ github.sha }}-${{ github.run_number }}
      - run: yarn test

  pr-success-slack:
    needs: [lint, test]
    if: ${{ success() }}
    name: Success notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: come25136/workflow-notification-for-slack@main
        with:
          include_jobs: true
          repo_token: ${{secrets.RRIOS_DEV_GITHUB_REPOSITORY }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: ${{github.repository}} - PR ready
          icon_emoji: ':art:'

  pr-failed-slack:
    needs: [lint, test]
    if: ${{ failure() }}
    name: Failed notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: come25136/workflow-notification-for-slack@main
        with:
          include_jobs: true
          repo_token: ${{secrets.RRIOS_DEV_GITHUB_REPOSITORY }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: ${{github.repository}} - PR failed
          icon_emoji: ':art:'
